import { Component } from '@angular/core';

@Component({
  selector: 'app-garden',
  templateUrl: 'garden.page.html',
  styleUrls: ['garden.page.scss']
})
export class GardenPage {

  searchTerm: string = '';
  trees = [
    { image: '../../assets/img/plants/dragon-fruit.jpg', alt: "Dragon Fruit - Hylocereus spp.", title: "Dragon Fruit - Hylocereus spp.", description: "The dragon fruit also known as (Hylocereus undatus) is a tropical fruit that belongs to the climbing cacti (Cactaceae) family. Widely cultivated in Vietnam, the fruit is popular in Southeast Asia. Apart from being refreshing and tasty, it has been noted that the dragon fruit is a rich source of vitamin C, calcium and phosphorus.", },
{ image: '../../assets/img/plants/mango.jpg', alt: "Mangga (Mango) - Mangifera indica", title: "Mangga (Mango) - Mangifera indica", description: "Mangifera indica (MI), also known as mango, it has been an important herb in the Ayurvedic and indigenous medical systems for over 4000 years. Mangoes belong to genus Mangifera which consists of about 30 species of tropical fruiting trees in the flowering plant family Anacardiaceae. According to ayurveda, varied medicinal properties are attributed to different parts of mango tree. Mango is one of the most popular of all tropical fruits. Mangiferin, being a polyphenolic antioxidant and a glucosyl xanthone, it has strong antioxidant, anti lipid peroxidation, immunomodulation, cardiotonic, hypotensive, wound healing, anti degenerative and antidiabetic activities.", },
{ image: '../../assets/img/plants/kalamansi.jpg', alt: "Kalamansi - Citrus microcarpa", title: "Kalamansi - Citrus microcarpa", description: "Calamansi (Citrus microcarpa) or Philippine lime, is an important local economic crop in Hainan China. It originated in Southeast Asia, mainly grow in Southeast Asia and tropical regions of China, and it had a long history of cultivation in Hainan Island. Calamansi fruit is rich in vitamins C, aromatic oils, carotenoids and other natural substances which have lots of health benefits for human, such as beneficial effects for human eyes, good for treating cough, asthma, high blood pressure and preventing arteriosclerosis etc. Calamansi fruit had a fine texture and sour taste. Calamansi juice is widely loved as a delicious fresh condiment.", },
{ image: '../../assets/img/plants/rambutan.jpg', alt: "Rambutan - Nephelium lappaceum", title: "Rambutan - Nephelium lappaceum", description: "Rambutan (Nephelium lappaceum) is a tropical fruit belonging to the family Sapindaceae. The word rambutan is derived from the Malay word rambut which means “hair”, a reference to the numerous hairy protuberances of the fruit. The fruit is often red but sometimes yellow. When peeled open, it reveals a sweet, white flesh clinging to a woody seed.", },
{ image: '../../assets/img/plants/atsuete.jpg', alt: "Atsuete - Bixa orellana", title: "Atsuete - Bixa orellana", description: "Atsuete also called Annatto (Bixa orellana) is a small tree native to the tropical region of Southern America. Atsuete is widely cultivated for its fruit seeds where a natural colorant is derived. Aside from the commercial value of Atsuete as a source of annatto colorant, Atsuete has long been used by the natives of Southern America as dye for food and textile, as decorative body paint, in spiritual ceremonies and rituals and as an herbal medicine.", },
{ image: '../../assets/img/plants/pechay.jpg', alt: "Pechay - Brassica rapa", title: "Pechay - Brassica rapa", description: "Pechay, scientifically known as Brassica rapa subsp, is a leafy green vegetable that is often overlooked despite its exceptional health benefits. Packed with essential nutrients and low in calories, the health benefits of pechay always catch detractors off-guard. It is rich in vitamins A, C, and K, as well as antioxidants that promote healthy skin, boost immunity, and fight inflammation.", },
{ image: '../../assets/img/plants/mango.jpg', alt: "Eggplant - Solanum melongena", title: "Eggplant - Solanum melongena", description: "Eggplant (Solanum melongena), commonly known as brinjal, aubergine, or guinea squash, belongs to the Solanaceae family and is included under the genus Solanum, one of the largest genera covering more than 1550 species. It is an important vegetable crop of tropical and temperate parts of the world. Eggplant is reported to exhibit antioxidative functions, to show anticancer effects, to lower cholesterol levels, and to reduce the risk of obesity, diabetes, and cardiovascular disease. This health-promoting ability of eggplant is attributed to the high content of phenols, mainly chlorogenic acid.", },
{ image: '../../assets/img/plants/lettuce.jpg', alt: "Lettuce - Lactuca sativa", title: "Lettuce - Lactuca sativa", description: "Lettuce, (Lactuca sativa), annual leaf vegetable of the aster family (Asteraceae). Most lettuce varieties are eaten fresh and are commonly served as the base of green salads. Lettuce is generally a rich source of vitamins K and A, though the nutritional quality varies, depending on the variety.", },
{ image: '../../assets/img/plants/guyabano.jpg', alt: "Guyabano - Annona muricata", title: "Guyabano - Annona muricata", description: "Annona muricata, commonly known as graviola or soursop or guyabano, is another tropical fruit tree in the Annonaceae family. This plant probably originated in the Antilles in the Caribbean. Soursop is cultivated in many countries such as Angola, Brazil, Colombia, Costa Rica, Cuba, Jamaica, Mexico, Panama, Peru, Puerto Rico, Venezuela, and SE Asia. Soursop fruit is derived from the fusion of many fruitlets. The fruit pulp consists of white fibrous juicy segments. Numerous black or dark brown seeds are embedded in a firm fleshy, acid-sweet, whitish pulp. It has more acidic flavor than cherimoya and resembles a mixture of pineapple and mango. The aroma volatiles of soursop consist of mainly esters (80%). Fruit is harvested when it is fully mature, firm, yellow-green, and with spines apart.", },
{ image: '../../assets/img/plants/wild-chili.jpg', alt: "Wild Chili - Capsicum annuum", title: "Wild Chili - Capsicum annuum", description: "Often mistaken for bird’s eye chili pepper, the cultivar siling labuyo is a species of capsicum fructescens in the capsicum genus. The name “siling labuyo” in Filipino means wild chili although at present this plant is widely cultivated because of its culinary importance in some Philippine dishes. The frail looking but fast growing plant probably got its name because it usually grows wildly almost anywhere in soil near a house.", },
{ image: '../../assets/img/plants/buko.jpg', alt: "Coconut Tree - Cocos nucifera", title: "Coconut Tree - Cocos nucifera", description: "Cocos nucifera (L.) (Arecaceae) is commonly called the “coconut tree” and is the most naturally widespread fruit plant on Earth. Throughout history, humans have used medicinal plants therapeutically, and minerals, plants, and animals have traditionally been the main sources of drugs. The constituents of C. nucifera have some biological effects, such as antihelminthic, anti-inflammatory, antinociceptive, antioxidant, antifungal, antimicrobial, and antitumor activities.", },
{ image: '../../assets/img/plants/crispa.jpg', alt: "Papaya - Carica papaya", title: "Papaya - Carica papaya", description: "Papaya (Carica papaya) is a herbaceous succulent plant popularly known as pawpaw, and belongs to the Caricaceae family. It is native to the tropics of the Americas but now is widely cultivated in other tropical regions of the world for its edible melon-like fruit, which is available throughout the year [125]. Different parts of the plant are employed in the treatment of different human and veterinary diseases in various parts of the world.", },
{ image: '../../assets/img/plants/pechay.jpg', alt: "Snake Plant - Sansevieria trifasciata", title: "Snake Plant - Sansevieria trifasciata", description: "Dracaena trifasciata, commonly known as snake plant, is a popular and hardy houseplant with stiff, sword-like leaves from six inches to 12 feet tall in its native habitat but usually reaches two feet tall when grown indoors. They vary in color but many have green-banded or striped leaves with a yellow or cream border. Snake plants are easy to grow and are nearly indestructible. They grow slowly indoors, adapting to both bright light and low-light corners, however a few hours of early morning direct sun can boost growth.", },
{ image: '../../assets/img/plants/rambutan.jpg', alt: "Ulam Raja - Cosmos caudatus", title: "Ulam Raja - Cosmos caudatus", description: "Ulam raja originates from Latin America and brought to Malaysia and other Southeast Asian countries through the Philippines. In Malay the word ulam raja literally means the “the King’s salad”. Ulam raja is one of the very popular Malaysia salad and served throughout the country from major hotels for tourists to buffet lunch and dinners.", },
{ image: '../../assets/img/plants/kalamansi.jpg', alt: "Talinum (may pinkish na bulaklak) - Talinum paniculatum", title: "Talinum (may pinkish na bulaklak) - Talinum paniculatum", description: "Waterleaf is a short-lived, erect, strongly branched, perennial plant with succulent stems 30 - 100cm tall growing from swollen, fleshy roots. The plant is often harvsted from the wild for local use as a food. It is also cultivated in various parts of the tropics for its edible leaves, being grown on a particularly large scale in Africa. It is sometimes planted as an ornamental pot plant or as an edging plant in gardens.", },
{ image: '../../assets/img/plants/lettuce.jpg', alt: "Nephrolepis cordifolia (Fern) - Nephrolepis cordifolia", title: "Nephrolepis cordifolia (Fern) - Nephrolepis cordifolia", description: "Leaves (fronds) are once pinnate that are up to 3 feet long and 2.8 inches wide.  Forty to one hundred leaflets (pinnae) may be found on each side of the main stalk of the frond with margins slightly or entirely toothed (serrated).  Rhizomes are suberect, with spreading, brown linear scales with hairlike tips; producing small ungerground tubers.", },
{ image: '../../assets/img/plants/mango.jpg', alt: "Golden Pandanus - Pandanus baptistii", title: "Golden Pandanus - Pandanus baptistii", description: "One of the most adaptable houseplants is Spider plant, Pandanus Variegated Spider plant has golden with Green-striped leaves. It produces long, thin, and slightly arched foliage. it is known by various common names like kewada, pandan, screw palm, screw pine, pandanus palm etc. It has various colors and shades, It is fairly easy to grow and care for, and it looks very beautiful in a hanging pot", },
{ image: '../../assets/img/plants/mugwort.jpg', alt: "Sweet Potato Leaves - Ipomoea batatas", title: "Sweet Potato Leaves - Ipomoea batatas", description: "Sweet potato leaves are medium to large in size and are cordate, or heart-shaped with pointed tips. The leaves grow in an alternate pattern and may be palmate or known as having multiple lobes depending on the variety. Sweet potato leaves range in color from dark to yellow-green or purple and tend to be darker on the surface and lighter on the underside. They grow on slender, green stems rising from long, creeping vines, and these vines can grow to four meters in length. The top ten centimeters of the leaves and stems are the most tender and the most commonly consumed. Sweet potato leaves have a slight bitterness when raw, but when cooked the leaves take on a mild, delicately sweet flavor with a taste similar to spinach and water spinach.", },
{ image: '../../assets/img/plants/mustasa.jpg', alt: "Senna alata - Senna alata", title: "Senna alata - Senna alata", description: "Senna alata (Linn)and Borreria ocymoides are enriched with flavonoids, saponins and anthraquinones and in a clinical investigation extracts from both plants were compared with conventional drugs (clotrimazole and griseofulvin)indicating better efficacy against dermatophytes isolated from 840 pupils, offering some hope in the treatment and management of the disease", },
{ image: '../../assets/img/plants/buko.jpg', alt: "Garden Croton - Codiaeum variegatum", title: "Garden Croton - Codiaeum variegatum", description: "Croton, a common houseplant in tropical Asia and the western Pacific, is a broadleaf evergreen perennial, shrub, and small tree native to the euphorbia family. Its striking foliage and numerous cultivars make it a popular choice for landscapes, gardens, and potted specimens in subtropical and tropical climates.", },
{ image: '../../assets/img/plants/papaya.jpg', alt: "Areca Palm (Palmera) - Dypsis lutescens", title: "Areca Palm (Palmera) - Dypsis lutescens", description: "Areca Palm Areca Palm, scientifically known as Dypsis lutescens, is a versatile plant native to Madagascar. It's popularly known as the Butterfly Palm or the Party Palm due to its feathery, yellow-green fronds that resemble butterfly wings. This palm is a favorite among plant enthusiasts for its adaptability to both indoor and outdoor environments.", },
{ image: '../../assets/img/plants/pechay.jpg', alt: "Spider Plant - Chlorophytum comosum", title: "Spider Plant - Chlorophytum comosum", description: "One of the most common and well-known of all houseplants. It is especially popular with beginners, being easy to grow and propagate, tolerant of neglect, and able to thrive in nearly any type of condition. It gets its common name from the small plantlets produced on long trailing stems that vaguely resemble spiders. This clump-forming, perennial, herbaceous plant, native to coastal areas of South Africa, has narrow, strap-shaped leaves arising from a central point. The leaves may be solid green or variegated with lengthwise stripes of white or yellow. The leaves are not flat, but appear channeled or folded down the middle. Plants grows 12-15″ tall. The thick, fleshy roots and rhizomes evolved to store water, allowing it to survive inconsistent watering", },
{ image: '../../assets/img/plants/rambutan.jpg', alt: "Baby Rubber Plant - Peperomia obtusifolia", title: "Baby Rubber Plant - Peperomia obtusifolia", description: "Native to South America, the Peperomia obtusifolia is a perennial flowering epiphyte plant species. In its natural habitat, it grows within high humidity forest areas making use of the nutrients provided by tree debris and the natural tropical environment. There are a number of cultivars, including the dark green leaves, variegated, and the Peperomia obtusifolia ‘Albomarginata’ that displays yellowy gold and green patched leaves", },
{ image: '../../assets/img/plants/sayote.jpg', alt: "Bird's Nest Fern - Asplenium nidus", title: "Bird's Nest Fern - Asplenium nidus", description: "The Bird's Nest Fern or Asplenium nidus is one of the several popular and beautiful ferns grown as houseplants. Ferns like this one can be grown in North facing windows perfectly well and will truly relish the type of light and cooler temperatures these places receive. In return the Bird's Nest Fern will give you lots of naturally glossy leaves arranged in a circular pattern which resemble a bird's nest", },
{ image: '../../assets/img/plants/seguine.jpg', alt: "Mugwort - Artemisia vulgaris", title: "Mugwort - Artemisia vulgaris", description: "Mugwort (Artemisia vulgaris) is a plant native to Europe, Asia, and Africa. The parts that grow above the ground and the root are used to make medicine.Chemicals in mugwort might have anti-inflammatory effects. It also contains a chemical called thujone, which might stimulate the uterus. People use mugwort for anxiety, irregular periods, colic, insomnia, and many other conditions, but there is no good scientific evidence to support these uses", },
{ image: '../../assets/img/plants/senna-alata.jpg', alt: "Aztec Marigold - Tagetes erecta", title: "Aztec Marigold - Tagetes erecta", description: "Taller and more upright than the shorter French marigold, the African marigold (Tagetes erecta) can mature to the grand height of three to four feet. A true annual that lasts only one season, the African marigold is a member of the aster family, with cultivars that offer large round flowers in shades of yellow, orange, and creamy white atop green stems and fern-like foliage.", },
{ image: '../../assets/img/plants/snake-plant.jpg', alt: "Asian Pigeon Wings - Clitoria ternatea", title: "Asian Pigeon Wings - Clitoria ternatea", description: "Asian pigeonwings is a legume with edible flowers. Flowers can be eaten raw or are dipped in batter and fried. Flowers can also be used as food colouring to colour glutinous rice, or are used to make Butterfly pea flower tea. In India the plant is a holy flower, used in rituals.", },
{ image: '../../assets/img/plants/spider-plant.jpg', alt: "Arrowleaf Elephant Ear - Xanthosoma sagittifolium", title: "Arrowleaf Elephant Ear - Xanthosoma sagittifolium", description: "Arrowleaf elephant's ear (*Xanthosoma sagittifolium*) is a herbaceous perennial that can grow from 3 to 3.5 m tall. It has large, blue-green, arrow-shaped leaves that resemble an elephant’s ear. The leaves can grow to 91 cm long, much larger than most elephant ear plants. It prefers partial to full shade", },
{ image: '../../assets/img/plants/sulfur-cosmos.jpg', alt: "Strobilanthes crispa - Strobilanthes crispus", title: "Strobilanthes crispa - Strobilanthes crispus", description: "Strobilanthes crispa is a shrub which originated from Madagascar, and is now found across south east Asia. It is a member of the family Acanthaceae. It is known as pokok pecah kaca or pokok pecah beling in Malaysia, and pecah beling, enyoh kilo, kecibeling or kejibeling in Indonesia", },
{ image: '../../assets/img/plants/sweet-potato-leaves.jpg', alt: "Sayote - Sechium edule", title: "Sayote - Sechium edule", description: "Sayote also called vegetable pear, mirliton, or chocho, perennial vine of the gourd family (Cucurbitaceae), cultivated for its edible fruits. Chayote is native to the New World tropics and is also grown as an annual plant in temperate climates. The fruits are boiled, baked, or sautéed as a vegetable and taste similarly to cooked cucumber or zucchini. Chayote can be eaten raw, though the peel contains a sap that can cause skin irritation in some people. The young tuberous roots are prepared like potatoes.", },
{ image: '../../assets/img/plants/talong.jpg', alt: "Mustasa - Brassica juncea", title: "Mustasa - Brassica juncea", description: "Brassica juncea  is a species of mustard plant. Peppery, crispy mustard greens, also known as leaf mustards. In the Philippines, it was known as Mustasa.  Mustard Greens are indeed one of the most nutritious green-leafy vegetables available around. Leaves eaten as green leafy vegetable, fresh or pickled in brine; also used in soups and stews. Its lovely top greens have actually more vitamin A, carotene, vitamin K, and flavonoid antioxidants than some of typical fruits and vegetables.", },
{ image: '../../assets/img/plants/ulam-raja.jpg', alt: "Dieffenbachia seguine - Dieffenbachia seguine", title: "Dieffenbachia seguine - Dieffenbachia seguine", description: "Dieffenbachia seguine is typically grown as a houseplant. It requires medium light levels and moderate indoor temperatures. This plant can be toxic for pets and children. This plant has an exotic appeal and has wonderfully shaped leaves with brush strokes of cream, yellow and white which enhance the shape of the leaves. The rich color of green with its brush strokes of color allow this plant to stand out and shout out to be seen in your home", },
{ image: '../../assets/img/plants/wild-chili.jpg', alt: "Aglaomorpha - Aglaonema spp.", title: "Aglaomorpha - Aglaonema spp.", description: "Aglaomorpha is a genus of ferns in the subfamily Drynarioideae of the family Polypodiaceae. The Pteridophyte Phylogeny Group classification of 2016 (PPG I) uses this genus name, while other sources use Drynaria to include Aglaomorpha. Species are commonly known as basket ferns. As circumscribed in PPG I, the genus contains around 50 species. Basket ferns are epiphytic or epipetric and are native to tropical Africa, South Asia, East Asia, Southeast Asia, Australia, and Oceania. Some species are economically important as medicinal plants.", },

  ];

  get filteredTrees() {
    return this.trees.filter((tree) => {
      const searchTermLower = this.searchTerm.toLowerCase();
      const titleLower = tree.title.toLowerCase();
      const descriptionLower = tree.description.toLowerCase();
      return titleLower.includes(searchTermLower) || descriptionLower.includes(searchTermLower);
    });
  }

}
